#pragma once

#define GRAPHIC_SETTING_MSG (WM_USER + 1)
#define SETTING_SET_MSG (WM_USER + 2)


#define ID_SETTING_MARGINLEFT 2
#define ID_SETTING_MARGINTOP 3
#define ID_SETTING_MARGINRIGHT 4
#define ID_SETTING_MARGINBOTTOM 5

#define ID_SETTING_LEFTHORIZONTALMARGINTEXT 6
#define ID_SETTING_BOTTOMHORIZONTALMARGINTEXT 7
#define ID_SETTING_LEFTVERTICALMARGINTEXT 8
#define ID_SETTING_BOTTOMVERTICALMARGINTEXT 9

#define ID_SETTING_COUNTCOORDLINES 10
#define ID_SETTING_COORDLINESLENGTH 11

#define ID_SETTING_COLORCOMBOBOX 12

#define ID_SETTING_XSTART 13
#define ID_SETTING_XEND 14
#define ID_SETTING_XSTEP 15

#define ID_SETTING_BUTTONSAVE 16
#define ID_SETTING_BUTTONCANCEL 17


#define ID_DY 18

#define ID_BTN_DRAWGRAPHIC 19


#define METHOD_EILER 20
#define METHOD_ADAMS 21

#define ID_RADIOBTN_EILER 22
#define ID_RADIOBTN_ADAMS 23


#define ID_ASM_EILER 24
#define ID_ASM_ADAMS 25

#define SCILAB 26